In [2]:
import numpy as np
test_array = np.arange(1,11)
array_sum = test_array.sum()
print("sum=",array_sum)


sum= 55


In [3]:
test_array2 = np.arange(1,13).reshape(3,4) # 1~12까지 3행 4열로 생성
print(test_array2)
array2_sum_raw = test_array2.sum(axis=0) # axis=0 (열의 방향으로 )
array2_sum_column= test_array2.sum(axis=1) # axis=1 (행의 방향으로)
print("열의 방향 합",array2_sum_raw)
print("행의 방향 합",array2_sum_column)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
열의 방향 합 [15 18 21 24]
행의 방향 합 [10 26 42]


In [6]:
#3차원 axis 합 예시
third_array = np.arange(1,13).reshape(3,4)
third_array_tensor = np.array([third_array,third_array,third_array])
third_array_tensor_axis0 = third_array_tensor.sum(axis=0)
third_array2_tensor_axis1 = third_array_tensor.sum(axis=1)
third_array2_tensor_axis2 = third_array_tensor.sum(axis=2)

print("3차원 행렬\n",third_array_tensor)
print("3차원 행렬 axis=0 합:\n ", third_array_tensor_axis0)
print("3차원 행렬 axis=1 합:\n ", third_array2_tensor_axis1)
print("3차원 행렬 axis=2 합:\n ", third_array2_tensor_axis2)

3차원 행렬
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3차원 행렬 axis=0 합:
  [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
3차원 행렬 axis=1 합:
  [[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
3차원 행렬 axis=2 합:
  [[10 26 42]
 [10 26 42]
 [10 26 42]]


In [8]:
#수학 연산 
test_array3= np.arange(1,13).reshape(3,4)
test_array3_mean = test_array3.mean() #전체 평균 계산
test_array3_mean_axis = test_array3.mean(axis=0) #축을 기준으로 평균(행)
test_array3_std = test_array3.std() #전체 표준편차
test_array3_std_axis=test_array3.std(axis=1) # 축을 기준으로 표준편차(열)
test_array3_sqrt = np.sqrt(test_array3) # 각 요소에 제곱근 연산

print("3x4 행렬:\n ", test_array3)
print("전체 평균:\n",test_array3_mean)
print("축 기준 평균:\n",test_array3_mean_axis) #axis=0 기준 -> 행 기준
print("전체 표준편차 :\n",test_array3_std)
print("축 기준 표준편차:\n",test_array3_std_axis) #axis=1 기준 ->열 기준 
print("각 요소 제곱근:\n",test_array3_sqrt)

3x4 행렬:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
전체 평균:
 6.5
축 기준 평균:
 [5. 6. 7. 8.]
전체 표준편차 :
 3.452052529534663
축 기준 표준편차:
 [1.11803399 1.11803399 1.11803399]
각 요소 제곱근:
 [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]
