In [3]:
#101페이지
import numpy as np

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
vstack_array=np.vstack((v1, v2)) #vstack() = vertical stack (수직 스택)
hstack_arrry=np.hstack((v1,v2)) #hsatck() = horizontal stack (수평 스택)
print("수직 스택 합:\n",vstack_array) #v1/v2를 수직으로 합침
print("수평 스택 합:\n",hstack_arrry) #v1/v2를 수평으로 합침

수직 스택 합:
 [[1 2 3 4]
 [5 6 7 8]]
수평 스택 합:
 [1 2 3 4 5 6 7 8]


In [5]:
re_v1 = v1.reshape(-1,1) # 열의 수는 1개 , 행의 수는 크기에 맞게 알아서
re_v2 = v2.reshape(-1,1)
print("re_v1:\n",re_v1,"\n","re_v2:\n",re_v2,"\n")
print("수평 스택: hstack(re_v1,re_v2)\n", np.hstack((re_v1,re_v2)))
print("수직 스택: vstack(re_v1,re_v2)\n", np.vstack((re_v1,re_v2)))

re_v1:
 [[1]
 [2]
 [3]
 [4]] 
 re_v2:
 [[5]
 [6]
 [7]
 [8]] 

수평 스택: hstack(re_v1,re_v2)
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
수직 스택: vstack(re_v1,re_v2)
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [8]:
v3= np.array([1,2,3,4]).reshape(2,2)
v4= np.array([[5,6]]).T # .T = 전치 매서드 (transpose) / 행을-> 열로 / 열을 -> 행으로/
print("v3:\n",v3)
print("v4:\n",v4)
concatenate_v3_v4 = np.concatenate((v3,v4),axis=1) # v1,v2를 axis=1을 기준으로 연결한다. *연결하려는 배열 간에 차원이 같아야 한다*
print("concatenate_v3_v4:\n",concatenate_v3_v4)

v3:
 [[1 2]
 [3 4]]
v4:
 [[5]
 [6]]
concatenate_v3_v4:
 [[1 2 5]
 [3 4 6]]


In [13]:
x= np.arange(1,7).reshape(2,3)
print("x배열:\n",x)
print("x+x:\n",x+x) # 행간 덧셈
print("x-x:\n",x-x) # 행간 뺄셈
print("x/x:\n",x/x) # 행간 나눗셈
print("x**x:\n",x**x) # 행간 제곱

x배열:
 [[1 2 3]
 [4 5 6]]
x+x:
 [[ 2  4  6]
 [ 8 10 12]]
x-x:
 [[0 0 0]
 [0 0 0]]
x/x:
 [[1. 1. 1.]
 [1. 1. 1.]]
x**x:
 [[    1     4    27]
 [  256  3125 46656]]


In [10]:
x_1= np.arange(1,7).reshape(2,3) #2x3 배열
x_2= np.arange(1,7).reshape(3,2) #3x2 배열

print("x_1:\n",x_1)
print("x_2:\n",x_2)
print("x_1.dot(x_2)\n",x_1.dot(x_2)) # 내적연산 (p.109) ->행 곱셈 

x_1:
 [[1 2 3]
 [4 5 6]]
x_2:
 [[1 2]
 [3 4]
 [5 6]]
x_1.dot(x_2)
 [[22 28]
 [49 64]]


In [11]:
y=np.arange(1,10).reshape(3,3) ## 스칼라 계산
print("y+10:\n",y+10)
print("y-2:\n",y-2)
print("y//3:\n",y//3)
print("y**2\n",y**2)

y+10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
y-2:
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
y//3:
 [[0 0 1]
 [1 1 2]
 [2 2 3]]
y**2
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [12]:
#브로드 캐스팅 연산 p.112
v=np.arange(1,13).reshape(4,3) # 4행 3열
z=np.arange(10,40,10) # 10부터 40까지 10을 간격으로 [10,20,30]
print("v:\n",v)
print("z:\n",z)
print("v+z:\n",v+z) # 브로드 캐스팅 연산 -> 4행 3열 + [10,20,30] 복제해서 4행으로 만듦 / 앞의 행렬에 맞춰서 벡터를 행렬로 만듦


v:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
z:
 [10 20 30]
v+z:
 [[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]
